# Generated by Django 3.2.7 on 2021-10-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='image_urls',
            new_name='image_url',
        ),
    ]
